Resources:
  MyNewEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08c84d37db8aafe00
      InstanceType: t2.micro
      SubnetId: subnet-0b66fe496afb21e9e
      SecurityGroupIds:
        - sg-0be9656f11b2eb854
      KeyName: EC2_Major
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd.x86_64
          systemctl start httpd.service
          systemctl enable httpd.service
          echo ?Hello World from $(hostname -f)? > /var/www/html/index.html
